/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/innovation': typeof InnovationRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/innovation': typeof InnovationRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/innovation': typeof InnovationRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/demo'
    | '/innovation'
    | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/architecture' | '/demo' | '/innovation' | '/scanner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/demo'
    | '/innovation'
    | '/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DemoRoute: typeof DemoRoute
  InnovationRoute: typeof InnovationRoute
  ScannerRoute: typeof ScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  DemoRoute: DemoRoute,
  InnovationRoute: InnovationRoute,
  ScannerRoute: ScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
